version: '3'

tasks:
  start:
    desc: Démarre tous les conteneurs
    cmds:
      - docker-compose up -d

  stop:
    desc: Arrête tous les conteneurs
    cmds:
      - docker-compose down

  install:
    desc: Installe les dépendances pour le frontend et le backend
    cmds:
      - docker-compose exec frontend npm install
      - docker-compose exec backend pip install -r requirements.txt

  test-unit-back:
    desc: Lance les tests unitaires du backend
    cmds:
      - docker-compose exec backend python manage.py test my_docker_django_app.tests.test_basic my_docker_django_app.tests.test_video authentification.tests.test_authentication

  test-e2e-playwright:
    desc: Lance les tests e2e
    cmds:
      - cd Front && cd my_front_app && npx playwright test tests/e2e/login.spec.ts

  test-unit-front:
    desc: Lance les tests unitaires du frontend
    cmds:
      - cd Front && cd my_front_app && npx jest test 

  logs:
    desc: Affiche les logs des conteneurs
    cmds:
      - docker-compose logs -f

  build:
    desc: Reconstruit les images Docker
    cmds:
      - docker-compose up --build
  front-server:
    desc: Lance le server front
    cmds: 
      - cd Front && cd my_front_app && npm run dev