# Generated by Django 5.1.6 on 2025-04-11 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_date', models.DateField(blank=True)),
                ('title', models.CharField(max_length=255)),
                ('thumbnail', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('published', 'Published'), ('draft', 'Draft')], default='draft', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('apprenant', 'Apprenant')], default='apprenant', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_date', models.DateField(blank=True)),
                ('title', models.CharField(max_length=255)),
                ('module_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_docker_django_app.module')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_date', models.DateField(blank=True)),
                ('title', models.CharField(max_length=255)),
                ('url_video', models.CharField(max_length=255)),
                ('module_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_docker_django_app.module')),
                ('section_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='my_docker_django_app.section')),
            ],
        ),
        migrations.AddField(
            model_name='module',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='my_docker_django_app.user'),
        ),
    ]
