# Generated by Django 5.1.6 on 2025-04-11 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_docker_django_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='module_id',
            new_name='module',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='section_id',
            new_name='section',
        ),
        migrations.RenameField(
            model_name='module',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='section',
            old_name='module_id',
            new_name='module',
        ),
    ]
