# Generated by Django 5.1.6 on 2025-04-11 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_docker_django_app', '0002_rename_module_id_lesson_module_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_docker_django_app.section'),
        ),
    ]
