# Generated by Django 5.1.6 on 2025-05-09 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_docker_django_app', '0004_alter_module_user_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='modification_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='module',
            name='modification_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='section',
            name='modification_date',
            field=models.DateField(auto_now=True),
        ),
    ]
