# Generated by Django 5.1.6 on 2025-06-27 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_docker_django_app', '0005_lesson_modification_date_module_modification_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='publication_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='my_docker_django_app.module'),
        ),
        migrations.AlterField(
            model_name='section',
            name='publication_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
