# Generated by Django 5.1.6 on 2025-06-15 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_docker_django_app', '0006_alter_lesson_publication_date_alter_section_module_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='publication_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='thumbnail',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
