# Generated by Django 5.1.6 on 2025-08-03 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_docker_django_app', '0007_alter_module_publication_date_alter_module_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='url_video',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
