# Generated by Django 5.1.6 on 2025-08-15 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_docker_django_app', '0009_alter_lesson_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='url_video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
