# Generated by Django 5.1.6 on 2025-09-26 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_docker_django_app', '0009_alter_lesson_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='detail',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='module',
            name='introduction',
            field=models.TextField(blank=True, default=''),
        ),
    ]
